"""
Takes the visuals manifest (either AI-generated video clips with
native audio, or free stock images with pan/zoom) plus narration text,
and assembles the final vertical short using JSON2Video.

AUDIO HANDLING:
- "video" scenes: the AI clip already contains native dialogue/audio
  generated by the video model (character speaking, sound effects,
  background music). NO separate narrator voice is added - that would
  overlap/clash with the clip's own audio.
- "image" scenes: stock photos have no audio at all, so an external
  narrator voice reads the narration text aloud, PLUS a background
  music track (randomly picked from MUSIC_LIBRARY for variety across
  videos) plays underneath at low volume.
"""

import os
import json
import random
import time
import requests

JSON2VIDEO_API_KEY = os.environ["JSON2VIDEO_API_KEY"]
BASE_URL = "https://api.json2video.com/v2"

HEADERS = {
    "x-api-key": JSON2VIDEO_API_KEY,
    "Content-Type": "application/json",
}

POLL_INTERVAL_SECONDS = 10
MAX_POLL_ATTEMPTS = 60

# Rotating background music library for IMAGE-format videos only (stock
# photos have no native audio, video-format clips generate their own).
# These must be real, publicly-hosted MP3 URLs - point them at files
# committed to this repo (raw.githubusercontent.com/.../music/track.mp3)
# or another public host. Add as many as you like for more variety;
# one is randomly picked per video. Leave the list empty to skip music
# entirely (safe default until real tracks are hosted).
MUSIC_LIBRARY = [
    "https://github.com/wasimwu01-a11y/Kidify-daily-video-pipeline/raw/refs/heads/main/music/apalonbeats-upbeat-upbeat-music-549422%20(1).mp3",
    "https://github.com/wasimwu01-a11y/Kidify-daily-video-pipeline/raw/refs/heads/main/music/apalonbeats-upbeat-upbeat-music-549422.mp3",
    "https://github.com/wasimwu01-a11y/Kidify-daily-video-pipeline/raw/refs/heads/main/music/atlasaudio-upbeat-and-inspiring-578932.mp3",
    "https://github.com/wasimwu01-a11y/Kidify-daily-video-pipeline/raw/refs/heads/main/music/sub_clair-ambient-instrumental-579510.mp3",
    "https://github.com/wasimwu01-a11y/Kidify-daily-video-pipeline/raw/refs/heads/main/music/sub_clair-dynamic-instrumental-579513.mp3",
    "https://github.com/wasimwu01-a11y/Kidify-daily-video-pipeline/raw/refs/heads/main/music/the_mountain-pop-upbeat-upbeat-pop-576584.mp3",
    "https://github.com/wasimwu01-a11y/Kidify-daily-video-pipeline/raw/refs/heads/main/music/the_mountain-upbeat-corporate-576594.mp3",
    "https://github.com/wasimwu01-a11y/Kidify-daily-video-pipeline/raw/refs/heads/main/music/the_mountain-upbeat-upbeat-music-567445.mp3",
    "https://github.com/wasimwu01-a11y/Kidify-daily-video-pipeline/raw/refs/heads/main/music/verclub_music-upbeat-550944.mp3",
]


def build_movie_json(manifest: list[dict], script: dict) -> dict:
    scenes = []
    visual_type = script.get("visual_type", "video")

    for scene in manifest:
        # Backward compatibility: manifests saved before the hybrid
        # image/video system used "clip_url" and had no "media_type"
        # (they were always video). Support both old and new formats.
        media_url = scene.get("media_url") or scene.get("clip_url")
        media_type = scene.get("media_type", "video")

        elements = []

        if media_type == "image":
            elements.append({
                "type": "image",
                "src": media_url,
                "resize": "cover",
                # Ken Burns style pan/zoom so a still photo doesn't
                # feel static.
                "zoom": 3,
            })
            # Stock images have no audio of their own - add the
            # external narrator voice for this scene.
            elements.append({
                "type": "voice",
                "text": scene["narration"],
                "voice": "en-US-EmmaMultilingualNeural",
            })
        else:
            elements.append({
                "type": "video",
                "src": media_url,
                "resize": "cover",
                # Do NOT mute this - the clip's native audio (character
                # dialogue, sound effects, music) IS the audio track.
                # No separate voice element added for video scenes.
            })

        if scene["on_screen_text"]:
            elements.append({
                "type": "text",
                "text": scene["on_screen_text"],
                "style": "007",
                "position": "top-center",
                "settings": {"font-size": 60, "font-weight": "bold"},
            })

        elements.append({
            "type": "subtitles",
            "settings": {"font-size": 48, "position": "bottom-center"},
        })

        scenes.append({
            "duration": scene["duration_seconds"],
            "elements": elements,
        })

    movie = {
        "resolution": "custom",
        "width": 1080,
        "height": 1920,
        "quality": "high",
        "scenes": scenes,
    }

    # Background music only for image-format videos (video-format clips
    # already have their own native background music/audio baked in -
    # adding another track would cause the same overlap problem we're
    # fixing here).
    if visual_type == "image" and MUSIC_LIBRARY:
        track = random.choice(MUSIC_LIBRARY)
        movie["elements"] = [
            {"type": "audio", "src": track, "volume": 0.15}
        ]

    return movie


def render(movie_json: dict) -> str:
    resp = requests.post(
        f"{BASE_URL}/movies",
        headers=HEADERS,
        json=movie_json,
        timeout=30,
    )
    resp.raise_for_status()
    project_id = resp.json()["project"]
    return project_id


def poll_for_render(project_id: str) -> str:
    for attempt in range(MAX_POLL_ATTEMPTS):
        resp = requests.get(
            f"{BASE_URL}/movies",
            headers=HEADERS,
            params={"project": project_id},
            timeout=30,
        )
        resp.raise_for_status()
        data = resp.json()

        if data.get("movie", {}).get("status") == "done":
            return data["movie"]["url"]
        if data.get("movie", {}).get("status") == "error":
            raise RuntimeError(f"JSON2Video render failed: {data}")

        time.sleep(POLL_INTERVAL_SECONDS)

    raise TimeoutError(f"JSON2Video render {project_id} did not finish in time")


def download_final_video(url: str, out_path: str):
    resp = requests.get(url, timeout=180)
    resp.raise_for_status()
    with open(out_path, "wb") as f:
        f.write(resp.content)


if __name__ == "__main__":
    script_path = os.environ.get("SCRIPT_OUTPUT_PATH", "script.json")
    manifest_path = os.environ.get("MANIFEST_OUTPUT_PATH", "clip_manifest.json")
    final_video_path = os.environ.get("FINAL_VIDEO_PATH", "final_video.mp4")

    with open(script_path) as f:
        script = json.load(f)
    with open(manifest_path) as f:
        manifest = json.load(f)

    movie_json = build_movie_json(manifest, script)
    project_id = render(movie_json)
    print(f"Render started: {project_id}")

    video_url = poll_for_render(project_id)
    download_final_video(video_url, final_video_path)

    print(f"Final video saved to {final_video_path}")
